### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::0()

### ISSUE THREAD

**Issue by SergeImprove** [czim/laravel-modelcomparer#1]
**Laravel version: 5.2
Package version: 0.9**

Got following error:
> BadMethodCallException: Call to undefined method Illuminate\Database\Query\Builder::0() in /home/vagrant/code/weerman/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2405
Stack trace:
#0 [internal function]: Illuminate\Database\Query\Builder->__call('0', Array)
#1 /home/vagrant/code/weerman/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1426): call_user_func_array(Array, Array)
#2 [internal function]: Illuminate\Database\Eloquent\Builder->__call('0', Array)
#3 /home/vagrant/code/weerman/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(3526): call_user_func_array(Array, Array)
#4 /home/vagrant/code/weerman/vendor/cartalyst/sentinel/src/Users/EloquentUser.php(443): Illuminate\Database\Eloquent\Model->__call('0', Array)
#5 /home/vagrant/code/weerman/vendor/czim/laravel-modelcomparer/src/Comparer/Comparer.php(310): Cartalyst\Sentinel\Users\EloquentUser->__call('0', Array)
#6 /home/vagrant/code/weerman/vendor/czim/laravel-modelcomparer/src/Comparer/Comparer.php(357): Czim\ModelComparer\Comparer\Comparer->buildNormalizedArrayTree(Object(App\Models\User), 'user')

After some investigation figured out that the error is related to **buildNormalizedArrayTree** method. If model relations not loaded, then $model->getRelations() returns following:
`array:2 [
  0 => "debtor"
  1 => "scopeDebtor"
]
`

In this case, **$relationKeys = array_keys($model->getRelations());** consists of 0 & 1 which is not a valid method names for model.

**Comment by czim** [comment]
I've looked at the relevant code for Laravel 5.2, which is no different from 5.3. 

The relations array is filled by logic that always assumes the keys are set. The whole logic of how the relations array on the model instance works, is based on it being a key (relation name) and value pair.

I'm very interested in your application setup and what makes it deviate from this norm. Are you setting the relations (loaded) status manually? What packages to you have installed that may tinker with the way Eloquent works?

**Comment by Blacksky13** [comment]
Ok, looks like my bad. For some reason, there was already filled property $relations:
```protected $relations = ['debtor', 'scopeDebtor'];```

That's why it received an indexed array instead of associative array.

Thank you for help!

**Comment by SergeImprove** [comment]
Ok, looks like my bad. For some reason, there was already filled property $relations:
```protected $relations = ['debtor', 'scopeDebtor'];```

That's why it received an indexed array instead of associative array.

Thank you for help!
